export default [
   
    {
       "cz":"péct",
       "infinitive":"backen",
       "pastTense":"backte",
       "pastTense2":"buk",
       "presentPerfect":"gebacken"
    },
    {
       "cz":"přikázat",
       "infinitive":"befehlen",
       "pastTense":"befahl",
       "presentPerfect2":"befohlen"
    },
    {
       "cz":"začít",
       "infinitive":"beginnen",
       "pastTense":"begann",
       "presentPerfect":"begonnen"
    },
    {
       "cz":"kousat",
       "infinitive":"beißen",
       "pastTense":"biss",
       "presentPerfect":"gebissen"
    },
    {
       "cz":"zachránit",
       "cz2": "vyprostit",
       "infinitive":"bergen",
       "pastTense":"barg",
       "presentPerfect":"geborgen"
    },
    {
       "cz":"prasknout",
       "infinitive":"bersten",
       "pastTense":"barst",
       "presentPerfect":"geborsten"
    },
    {
       "cz":"podvést",
       "infinitive":"betrügen",
       "pastTense":"betrog",
       "presentPerfect":"betrogen"
    },
    {
       "cz":"hnout",
       "infinitive":"bewegen",
       "pastTense":"bewog",
       "presentPerfect":"bewogen"
    },
    {
       "cz":"ohnout",
       "infinitive":"biegen",
       "pastTense":"bog",
       "presentPerfect":"gebogen"
    },
    {
       "cz":"nabídnout",
       "infinitive":"bieten",
       "pastTense":"bot",
       "presentPerfect":"geboten"
    },
    {
       "cz":"vázat",
       "infinitive":"binden",
       "pastTense":"band",
       "presentPerfect":"gebunden"
    },
    {
       "cz":"prosit",
       "infinitive":"bitten",
       "pastTense":"bat",
       "presentPerfect":"gebeten"
    },
    {
       "cz":"foukat",
       "infinitive":"blasen",
       "pastTense":"blies",
       "presentPerfect":"geblasen"
    },
    {
       "cz":"zůstat",
       "infinitive":"bleiben",
       "pastTense":"blieb",
       "presentPerfect":"bleiben"
    },
    {
       "cz":"péct",
       "infinitive":"braten",
       "pastTense":"briet",
       "presentPerfect":"gebraten"
    },
    {
       "cz":"lámat",
       "infinitive":"brechen",
       "pastTense":"brach",
       "presentPerfect":"gebrochen"
    },
    {
       "cz":"hořet",
       "infinitive":"brennen",
       "pastTense":"brannte",
       "presentPerfect":"gebrannt"
    },
    {
       "cz":"přinést",
       "infinitive":"bringen",
       "pastTense":"brachte",
       "presentPerfect":"gebracht"
    },
    {
       "cz":"myslet",
       "infinitive":"denken",
       "pastTense":"dachte",
       "presentPerfect":"gedacht"
    },
    {
       "cz":"najmout",
       "infinitive":"dingen",
       "pastTense":"dang",
       "presentPerfect":"gedungen"
    },
    {
       "cz":"mlátit",
       "infinitive":"dreschen",
       "pastTense":"drosch",
       "presentPerfect":"gedroschen"
    },
    {
       "cz":"pronikat",
       "infinitive":"dringen",
       "pastTense":"drang",
       "presentPerfect":"gedrungen"
    },
    {
       "cz":"přijmout",
       "cz2": "uvítat",
       "infinitive":"empfangen",
       "pastTense":"empfing",
       "presentPerfect":"empfangen"
    },
    {
       "cz":"přijmout",
       "infinitive":"empfehlen",
       "pastTense":"empfahl",
       "presentPerfect":"empfohlen"
    },
    {
       "cz":"cítit",
       "infinitive":"empfinden",
       "pastTense":"empfand",
       "presentPerfect":"empfunden"
    },
    {
       "cz":"vyblednout",
       "infinitive":"erbleichen",
       "pastTense":"erbleichte",
       "pastTense2":"erblich",
       "presentPerfect":"erbleichte",
       "presentPerfect2":"erblichen"
    },
    {
       "cz":"zhasnout",
       "cz2": "zaniknout",
       "infinitive":"erlöschen",
       "pastTense":"erlosch",
       "presentPerfect":"erloschen"
    },
    {
       "cz":"polekat se",
       "cz2":"vyděsit se",
       "infinitive":"erschrecken",
       "pastTense":"erschrak",
       "presentPerfect":"erschrocken"
    },
    {
       "cz":"uvážit",
       "cz2": "zvážit",
       "infinitive":"erwägen",
       "pastTense":"erwog",
       "presentPerfect":"erwogen"
    },
    {
       "cz":"jíst",
       "infinitive":"essen",
       "pastTense":"aß",
       "presentPerfect":"gegessen"
    },
    {
       "cz":"jet",
       "infinitive":"fahren",
       "pastTense":"fuhr",
       "presentPerfect":"gefahren"
    },
    {
       "cz":"padat",
       "infinitive":"fallen",
       "pastTense":"fiel",
       "presentPerfect":"gefallen"
    },
    {
       "cz":"chytit",
       "infinitive":"fangen",
       "pastTense":"fing",
       "presentPerfect":"gefangen"
    },
    {
       "cz":"šermovat",
       "infinitive":"fechten",
       "pastTense":"focht",
       "presentPerfect":"gefochten"
    },
    {
       "cz":"najít",
       "infinitive":"finden",
       "pastTense":"fand",
       "presentPerfect":"gefunden"
    },
    {
       "cz":"uplést",
       "infinitive":"flechten",
       "pastTense":"flocht",
       "presentPerfect":"geflochten"
    },
    {
       "cz":"letět",
       "infinitive":"fliegen",
       "pastTense":"flog",
       "presentPerfect":"geflogen"
    },
    {
       "cz":"uprchnout",
       "infinitive":"fliehen",
       "pastTense":"floh",
       "presentPerfect":"geflohen"
    },
    {
       "cz":"téct",
       "cz2": "plynout",
       "infinitive":"fließen",
       "pastTense":"floss",
       "presentPerfect":"geflossen"
    },
    {
       "cz":"žrát",
       "infinitive":"fressen",
       "pastTense":"fraß",
       "presentPerfect":"gefressen"
    },
    {
       "cz":"mrznout",
       "infinitive":"frieren",
       "pastTense":"fror",
       "presentPerfect":"gefroren"
    },
    {
       "cz":"kvasit",
       "infinitive":"gären",
       "pastTense":"gor",
       "presentPerfect":"gegoren"
    },
    {
       "cz":"",
       "infinitive":"gebären",
       "pastTense":"gebar",
       "presentPerfect":"geboren"
    },
    {
       "cz":"rodit",
       "cz2": "porodit",
       "infinitive":"geben",
       "pastTense":"gab",
       "presentPerfect":"gegeben"
    },
    {
       "cz":"dařit se",
       "infinitive":"gedeihen",
       "pastTense":"gedieh",
       "presentPerfect":"gediehen"
    },
    {
       "cz":"jít",
       "infinitive":"gehen",
       "pastTense":"ging",
       "presentPerfect":"gegangen"
    },
    {
       "cz":"podařit se",
       "infinitive":"gelingen",
       "pastTense":"gelang",
       "presentPerfect":"gelungen"
    },
    {
       "cz":"platit",
       "infinitive":"gelten",
       "pastTense":"galt",
       "presentPerfect":"gegolten"
    },
    {
       "cz":"zotavit",
       "cz2":"uzdravit",
       "infinitive":"genesen",
       "pastTense":"genas",
       "presentPerfect":"genesen"
    },
    {
       "cz":"užívat si",
       "infinitive":"genießen",
       "pastTense":"genoss",
       "presentPerfect":"genossen"
    },
    {
       "cz":"stát se",
       "infinitive":"geschehen",
       "pastTense":"geschah",
       "presentPerfect":"geschehen"
    },
    {
       "cz":"vyhrát",
       "infinitive":"gewinnen",
       "pastTense":"gewann",
       "presentPerfect":"gewonnen"
    },
    {
       "cz":"zalévat",
       "cz2": "lít",
       "infinitive":"gießen",
       "pastTense":"goss",
       "presentPerfect":"gegossen"
    },
    {
       "cz":"podobat se",
       "infinitive":"gleichen",
       "pastTense":"glich",
       "presentPerfect":"geglichen"
    },
    {
       "cz":"klouzat",
       "infinitive":"gleiten",
       "pastTense":"glitt",
       "presentPerfect":"geglitten"
    },
    {
       "cz":"doutnat",
       "cz2": "žhnout",
       "infinitive":"glimmen",
       "pastTense":"glomm",
       "presentPerfect":"geglommen"
    },
    {
       "cz":"kopat",
       "cz2": "těžit",
       "infinitive":"graben",
       "pastTense":"grub",
       "presentPerfect":"gegraben"
    },
    {
       "cz":"chytit",
       "cz2": "lapit",
       "infinitive":"greifen",
       "pastTense":"griff",
       "presentPerfect":"gegriffen"
    },
    {
       "cz":"stát",
       "infinitive":"halten",
       "pastTense":"hielt",
       "presentPerfect":"gehalten"
    },
    {
       "cz":"viset",
       "infinitive":"hängen",
       "pastTense":"hing",
       "presentPerfect":"gehangen"
    },
    {
       "cz":"prát se",
       "infinitive":"hauen",
       "pastTense":"haute ",
       "pastTense2":"hieb",
       "presentPerfect":"gehauen"
    },
    {
       "cz":"zvednout",
       "infinitive":"heben",
       "pastTense":"hob",
       "presentPerfect":"gehoben"
    },
    {
       "cz":"jmenovat se",
       "infinitive":"heißen",
       "pastTense":"hieß",
       "presentPerfect":"geheißen"
    },
    {
       "cz":"pomoci",
       "infinitive":"helfen",
       "pastTense":"half",
       "presentPerfect":"hat geholfen"
    },
    {
       "cz":"znát",
       "infinitive":"kennen",
       "pastTense":"kannte",
       "presentPerfect":"gekannt"
    },
    {
       "cz":"lézt",
       "infinitive":"klimmen",
       "pastTense":"klomm",
       "presentPerfect":"geklommen"
    },
    {
       "cz":"znít",
       "cz2": "zvonit",
       "infinitive":"klingen",
       "pastTense":"klang",
       "presentPerfect":"geklungen"
    },
    {
       "cz":"štípnout",
       "cz2": "škrtit",
       "infinitive":"kneifen",
       "pastTense":"kniff",
       "presentPerfect":"gekniffen"
    },
    {
       "cz":"přijít",
       "infinitive":"kommen",
       "pastTense":"kam",
       "presentPerfect":"gekommen"
    },
    {
       "cz":"plazit se",
       "infinitive":"kriechen",
       "pastTense":"kroch",
       "presentPerfect":"gekrochen"
    },
    {
       "cz":"naložit",
       "infinitive":"laden",
       "pastTense":"lud",
       "presentPerfect":"geladen"
    },
    {
       "cz":"nechat",
       "infinitive":"lassen",
       "pastTense":"ließ",
       "presentPerfect":"gelassen"
    },
    {
       "cz":"běžet",
       "infinitive":"laufen",
       "pastTense":"lief",
       "presentPerfect":"gelaufen"
    },
    {
       "cz":"trpět",
       "infinitive":"leiden",
       "pastTense":"litt",
       "presentPerfect":"gelitten"
    },
    {
       "cz":"půjčit",
       "infinitive":"leihen",
       "pastTense":"lieh",
       "presentPerfect":"geliehen"
    },
    {
       "cz":"číst",
       "infinitive":"lesen",
       "pastTense":"las",
       "presentPerfect":"gelesen"
    },
    {
       "cz":"ležet",
       "infinitive":"liegen",
       "pastTense":"lag",
       "presentPerfect":"gelegen"
    },
    {
       "cz":"lhát",
       "infinitive":"lügen",
       "pastTense":"log",
       "presentPerfect":"gelogen"
    },
    {
       "cz":"mlít",
       "infinitive":"mahlen",
       "pastTense":"mahlte",
       "presentPerfect":"gemahlen"
    },
    {
       "cz":"vyhýbat se",
       "infinitive":"meiden",
       "pastTense":"mied",
       "presentPerfect":"gemieden"
    },
    {
       "cz":"dojit",
       "infinitive":"melken",
       "pastTense":"melkte",
       "pastTense2":"molk",
       "presentPerfect":"gemelkt",
       "presentPerfect2":"gemolken"
    },
    {
       "cz":"měřit",
       "infinitive":"messen",
       "pastTense":"maß",
       "presentPerfect":"gemessen"
    },
    {
       "cz":"nepodařit se",
       "infinitive":"misslingen",
       "pastTense":"misslang",
       "presentPerfect":"misslungen"
    },
    {
       "cz":"vzít",
       "infinitive":"nehmen",
       "pastTense":"nahm",
       "presentPerfect":"genommen"
    },
    {
       "cz":"nazývat se",
       "infinitive":"nennen",
       "pastTense":"nannte",
       "presentPerfect":"genannt"
    },
    {
       "cz":"pískat",
       "infinitive":"pfeifen",
       "pastTense":"pfiff",
       "presentPerfect":"gepfiffen"
    },
    {
       "cz":"chválit",
       "infinitive":"preisen",
       "pastTense":"pries",
       "presentPerfect":"gepriesen"
    },
    {
       "cz":"proudit",
       "infinitive":"quellen",
       "pastTense":"quoll",
       "presentPerfect":"gequollen"
    },
    {
       "cz":"hádat",
       "cz2": "radit",
       "infinitive":"raten",
       "pastTense":"riet",
       "presentPerfect":"geraten"
    },
    {
       "cz":"utřít",
       "infinitive":"reiben",
       "pastTense":"rieb",
       "presentPerfect":"gerieben"
    },
    {
       "cz":"cestovat",
       "infinitive":"reißen",
       "pastTense":"riss",
       "presentPerfect":"gerissen"
    },
    {
       "cz":"jet na koni",
       "infinitive":"reiten",
       "pastTense":"ritt",
       "presentPerfect":"geritten"
    },
    {
       "cz":"běžet",
       "infinitive":"rennen",
       "pastTense":"rannte",
       "presentPerfect":"gerannt"
    },
    {
       "cz":"vonět",
       "cz2": "čichat",
       "infinitive":"riechen",
       "pastTense":"roch",
       "presentPerfect":"gerochen"
    },
    {
       "cz":"zápasit",
       "cz2": "usilovat",
       "infinitive":"ringen",
       "pastTense":"rang",
       "presentPerfect":"gerungen"
    },
    {
       "cz":"sypat se",
       "cz2": "téci",
       "infinitive":"rinnen",
       "pastTense":"rann",
       "presentPerfect":"geronnen"
    },
    {
       "cz":"volat",
       "infinitive":"rufen",
       "pastTense":"rief",
       "presentPerfect":"gerufen"
    },
    {
       "cz":"solit",
       "infinitive":"salzen",
       "pastTense":"salzte",
       "presentPerfect":"gesalzen",
       "presentPerfect2":"gesaltzt"
    },
    {
       "cz":"chlastat",
       "infinitive":"saufen",
       "pastTense":"soff",
       "presentPerfect":"gesoffen"
    },
    {
       "cz":"vysát",
       "infinitive":"saugen",
       "pastTense":"saugte",
       "pastTense2":"sog",
       "presentPerfect":"gesaugt",
       "presentPerfect2":"gesogt"
    },
    {
       "cz":"zvládnout",
       "cz2": "stvořit",
       "infinitive":"schaffen",
       "pastTense":"schuf",
       "presentPerfect":"geschaffen"
    },
    {
       "cz":"rozvést",
       "cz2":"oddělit",
       "infinitive":"scheiden",
       "pastTense":"schied",
       "presentPerfect":"geschieden"
    },
    {
       "cz":"rozvést",
       "infinitive":"scheinen",
       "pastTense":"schien",
       "presentPerfect":"geschienen"
    },
    {
       "cz":"srát",
       "infinitive":"scheißen",
       "pastTense":"schiss",
       "presentPerfect":"geschissen"
    },
    {
       "cz":"nadávat",
       "infinitive":"schelten",
       "pastTense":"schalt",
       "presentPerfect":"gescholten"
    },
    {
       "cz":"stříhat",
       "infinitive":"scheren",
       "pastTense":"schor",
       "presentPerfect":"geschoren"
    },
    {
       "cz":"sunout",
       "cz2": "tlačit",
       "infinitive":"schieben",
       "pastTense":"schob",
       "presentPerfect":"geschoben"
    },
    {
       "cz":"střílet",
       "infinitive":"schießen",
       "pastTense":"schoss",
       "presentPerfect":"geschossen"
    },
    {
       "cz":"spát",
       "infinitive":"schlafen",
       "pastTense":"schlief",
       "presentPerfect":"geschlafen"
    },
    {
       "cz":"bít",
       "cz2": "tlouci",
       "infinitive":"schlagen",
       "pastTense":"schlug",
       "presentPerfect":"geschlagen"
    },
    {
       "cz":"plížit se",
       "infinitive":"schleichen",
       "pastTense":"schlich",
       "presentPerfect":"geschlichen"
    },
    {
       "cz":"brousit",
       "cz2": "cepovat",
       "infinitive":"schleifen",
       "pastTense":"schliff",
       "presentPerfect":"geschliffen"
    },
    {
       "cz":"zavřít",
       "infinitive":"schließen",
       "pastTense":"schloss",
       "presentPerfect":"geschlossen"
    },
    {
       "cz":"ovázat",
       "cz2": "obejmout",
       "infinitive":"schlingen",
       "pastTense":"schlang",
       "presentPerfect":"geschlungen"
    },
    {
       "cz":"mrštit",
       "cz2": "praštit", 
       "infinitive":"schmeißen",
       "pastTense":"schmiss",
       "presentPerfect":"geschmissen"
    },
    {
       "cz":"mrštit",
       "infinitive":"schmelzen",
       "pastTense":"schmolz",
       "presentPerfect":"geschmolzen"
    },
    {
       "cz":"krájet",
       "infinitive":"schneiden",
       "pastTense":"schnitt",
       "presentPerfect":"geschnitten"
    },
    {
       "cz":"psát",
       "infinitive":"schreiben",
       "pastTense":"schrieb",
       "presentPerfect":"geschrieben"
    },
    {
       "cz":"řvát",
       "infinitive":"schreien",
       "pastTense":"schrie",
       "presentPerfect":"geschrie(e)n"
    },
    {
       "cz":"kráčet",
       "infinitive":"schreiten",
       "pastTense":"schritt",
       "presentPerfect":"geschritten"
    },
    {
       "cz":"mlčet",
       "infinitive":"schweigen",
       "pastTense":"schwieg",
       "presentPerfect":"geschwiegen"
    },
    {
       "cz":"otéct",
       "infinitive":"schwellen",
       "pastTense":"schwoll",
       "presentPerfect":"geschwollen"
    },
    {
       "cz":"plavat",
       "infinitive":"schwimmen",
       "pastTense":"schwamm",
       "presentPerfect":"geschwommen"
    },
    {
       "cz":"houpat se",
       "infinitive":"schwingen",
       "pastTense":"schwang",
       "presentPerfect":"geschwungen"
    },
    {
       "cz":"přísahat",
       "infinitive":"schwören",
       "pastTense":"schwor",
       "presentPerfect":"geschworen"
    },
    {
       "cz":"vidět",
       "infinitive":"sehen",
       "pastTense":"sah",
       "presentPerfect":"gesehen"
    },
    {
       "cz":"poslat",
       "infinitive":"senden",
       "pastTense":"sandte",
       "presentPerfect":"gesandt"
    },
    {
       "cz":"zpívat",
       "infinitive":"singen",
       "pastTense":"sang",
       "presentPerfect":"gesungen"
    },
    {
       "cz":"klesat",
       "cz2": "potápět",
       "infinitive":"sinken",
       "pastTense":"sank",
       "presentPerfect":"gesunken"
    },
    {
       "cz":"dumat",
       "infinitive":"sinnen",
       "pastTense":"sann",
       "presentPerfect":"gesonnen"
    },
    {
       "cz":"sedět",
       "infinitive":"sitzen",
       "pastTense":"saß",
       "presentPerfect":"gesessen"
    },
    {
       "cz":"",
       "infinitive":"spalten",
       "pastTense":"spaltete",
       "presentPerfect":"gespalten"
    },
    {
       "cz":"",
       "infinitive":"speien",
       "pastTense":"spie",
       "presentPerfect":"gespie(e)n"
    },
    {
       "cz":"štípat",
       "cz2": "štěpit",
       "infinitive":"spinnen",
       "pastTense":"spann",
       "presentPerfect":"gesponnen"
    },
    {
       "cz":"mluvit",
       "infinitive":"sprechen",
       "pastTense":"sprach",
       "presentPerfect":"gesprochen"
    },
    {
       "cz":"klíčit",
       "cz2": "rašit",
       "infinitive":"sprießen",
       "pastTense":"spross",
       "presentPerfect":"gesprossen"
    },
    {
       "cz":"skákat",
       "infinitive":"springen",
       "pastTense":"sprang",
       "presentPerfect":"gesprungen"
    },
    {
       "cz":"štípat",
       "cz2": "píchat",
       "infinitive":"stechen",
       "pastTense":"stach",
       "presentPerfect":"gestochen"
    },
    {
       "cz":"stát",
       "infinitive":"stehen",
       "pastTense":"stand",
       "presentPerfect":"gestanden"
    },
    {
       "cz":"krást",
       "infinitive":"stehlen",
       "pastTense":"stahl",
       "presentPerfect":"gestohlen"
    },
    {
       "cz":"stoupat",
       "infinitive":"steigen",
       "pastTense":"stieg",
       "presentPerfect":"gestiegen"
    },
    {
       "cz":"zemřít",
       "infinitive":"sterben",
       "pastTense":"starb",
       "presentPerfect":"gestorben"
    },
    {
       "cz":"vířit",
       "cz2": "rozprchnout",
       "infinitive":"stieben",
       "pastTense":"stob",
       "presentPerfect":"gestoben"
    },
    {
       "cz":"smrdět",
       "infinitive":"stinken",
       "pastTense":"stank",
       "presentPerfect":"gestunken"
    },
    {
       "cz":"narazit",
       "cz2": "narazit",
       "infinitive":"stoßen",
       "pastTense":"stieß",
       "presentPerfect":"gestoßen"
    },
    {
       "cz":"pohladit",
       "cz2": "rozetřít",
       "infinitive":"streichen",
       "pastTense":"strich",
       "presentPerfect":"gestrichen"
    },
    {
       "cz":"hádat se",
       "infinitive":"streiten",
       "pastTense":"stritt",
       "presentPerfect":"gestritten"
    },
    {
       "cz":"nosit",
       "infinitive":"tragen",
       "pastTense":"trug",
       "presentPerfect":"getragen"
    },
    {
       "cz":"trefit",
       "cz2": "zasáhnout",
       "infinitive":"treffen",
       "pastTense":"traf",
       "presentPerfect":"getroffen"
    },
    {
       "cz":"hnát",
       "infinitive":"treiben",
       "pastTense":"trieb",
       "presentPerfect":"getrieben"
    },
    {
       "cz":"vstoupit",
       "infinitive":"treten",
       "pastTense":"trat",
       "presentPerfect":"getreten"
    },
    {
       "cz":"pít",
       "infinitive":"trinken",
       "pastTense":"trank",
       "presentPerfect":"getrunken"
    },
    {
       "cz":"klamat",
       "infinitive":"trügen",
       "pastTense":"trug",
       ",pr{esentPerfect":"getrogen"
    },
    {
       "cz":"dělat",
       "infinitive":"tun",
       "pastTense":"tat",
       "presentPerfect":"getan"
    },
    {
       "cz":"vyblednout",
       "infinitive":"verbleichen",
       "pastTense":"verblich",
       "presentPerfect":"verblichen"
    },
    {
       "cz":"zkazit se",
       "infinitive":"verderben",
       "pastTense":"verdarb",
       "presentPerfect":"verdorben"
    },
    {
       "cz":"mrzet",
       "infinitive":"verdrießen",
       "pastTense":"verdross",
       "presentPerfect":"verdrossen"
    },
    {
       "cz":"zapomenout",
       "infinitive":"vergessen",
       "pastTense":"vergaß",
       "presentPerfect":"vergessen"
    },
    {
       "cz":"ztratit",
       "infinitive":"verlieren",
       "pastTense":"verlor",
       "presentPerfect":"verloren"
    },
    {
       "cz":"zmizet",
       "infinitive":"verschwinden",
       "pastTense":"verschwand",
       "presentPerfect":"verschwunden"
    },
    {
       "cz":"prominout",
       "infinitive":"verzeihen",
       "pastTense":"verzieh",
       "presentPerfect":"verziehen"
    },
    {
       "cz":"růst",
       "infinitive":"wachsen",
       "pastTense":"wuchs",
       "presentPerfect":"gewachsen"
    },
    {
       "cz":"mýt",
       "infinitive":"waschen",
       "pastTense":"wusch",
       "presentPerfect":"gewaschen"
    },
    {
       "cz":"ustoupit",
       "cz2": "namočit",
       "infinitive":"weichen",
       "pastTense":"wich",
       "presentPerfect":"gewichen"
    },
    {
       "cz":"ukázat",
       "infinitive":"weisen",
       "pastTense":"wies",
       "presentPerfect":"gewiesen"
    },
    {
       "cz":"otočit",
       "infinitive":"wenden",
       "pastTense":"wandte",
       "presentPerfect":"gewandt"
    },
    {
       "cz":"propagovat",
       "infinitive":"werben",
       "pastTense":"warb",
       "presentPerfect":"geworben"
    },
    {
       "cz":"hodit",
       "infinitive":"werfen",
       "pastTense":"warf",
       "presentPerfect":"geworfen"
    },
    {
       "cz":"vážit",
       "infinitive":"wiegen",
       "pastTense":"wog",
       "presentPerfect":"gewogen"
    },
    {
       "cz":"vinout",
       "cz2": "navíjet",
       "infinitive":"winden",
       "pastTense":"wand",
       "presentPerfect":"gewunden"
    },
    {
       "cz":"vědět",
       "infinitive":"wissen",
       "pastTense":"wusste",
       "presentPerfect":"gewusst"
    },
    {
       "cz":"ždímat",
       "infinitive":"wringen",
       "pastTense":"wrang",
       "presentPerfect":"gewrungen"
    },
    {
       "cz":"táhnout",
       "infinitive":"ziehen",
       "pastTense":"zog",
       "presentPerfect":"gezogen"
    },
    {
       "cz":"nutit",
       "infinitive":"zwingen",
       "pastTense":"zwang",
       "presentPerfect":"gezwungen"
    }
]